### ISSUE TITLE
Issue with PPS and CMake link

### ISSUE THREAD

**Issue by oxoocoffee** [Simmesimme/Simmesimme.github.io#1]
I noticed that this link among few others its dead

http://simmesimme.github.io/lessons/2011/11/02/ppa-launchpad-cmake. This is exactly what I was looking for :)

**Comment by Simmesimme** [comment]
Mhhh, interesting. Thanks for the report, maybe that's an github issue. Until it is fixed, you can use the google cache version:

http://webcache.googleusercontent.com/search?q=cache:http://simmesimme.github.io/lessons/2011/11/02/ppa-launchpad-cmake&gws_rd=cr&ei=JWQxWLGYMMWxaq-wmaAO

**Comment by Simmesimme** [comment]
Update: I triggered a rebuild by pushing an empty commit - now it works again! Thank you!
